### PR TITLE
Changed AnyError's implementation of NetworkServiceFailureInitializable

### PR DESCRIPTION
**Pull request by rickbdotcom**
To allow access to underlying failureResponse.

### CODE REVIEW

**Comment by wmcginty** [comment]
Thanks for the contribution @rickbdotcom ! The changes look good to me - can you fix the resulting broken unit tests and add a changeling entry before merging?

**Comment by rickbdotcom** [comment]
Will do!

**Comment by wmcginty** [comment]
@rickbdotcom This looks great, if you can just add an entry to `Changelog.md` I think we're good to go!

**Comment by rickbdotcom** [comment]
OK updated change log. Now one issue I can see with this change is that it could break some code if a consumer of the Framework was depending on the underlying error being NetworkServiceError and doing a cast of AnyError.error to NetworkServiceError.

**Comment by wmcginty** [comment]
@rickbdotcom I don't think that's a huge issue assuming we bump the minor version number and call the impact of the change out. Thoughts @tylermilner ?

**Comment by tylermilner** [comment]
@wmcginty sounds good to me. @rickbdotcom looks like there's a conflict in `CHANGELOG.md`. Could you resolve so that we can merge?

**Pull request merged**
