### PR TITLE
Added `execute()` method that accepts a request that's `Recoverable` to `BackendServiceProtocol`.

### PR DESCRIPTION
**Pull request by tylermilner**

### CODE REVIEW

**Comment by wmcginty** [comment]
Haha, I literally made a branch that did this almost exact thing the other day (I've been making sure it works before creating a PR). I think the only additional things I did were add an `requestRecoveryStrategy: RequestRecoveryStrategy?` to `BackendServiceProtocol` and provide a convenience converter to a `Future<Response, Error>`

**Comment by tylermilner** [comment]
It sounds like your approach might be more complete than what I've got here, @wmcginty. I'm fine if we want to use your implementation. Would you say your branch is good to go? If so, I'll close this and point my app to your branch for the time being. Unfortunately, this is something I need ASAP so that I can finish up a feature to recover from 401 errors and ship today.

**Comment by wmcginty** [comment]
It fixed my issue - I'll throw up a PR now and you can take a look. Happy to merge quickly if you need.

**Comment by tylermilner** [comment]
Closing...these changes will be implemented as part of #110.

**Pull request closed without merging**
