### PR TITLE
fix 3.0.0 changelog

### PR DESCRIPTION
**Pull request by pranjalsatija**

### CODE REVIEW

**Comment by wmcginty** [comment]
Nevermind approved it, who's the fool that wrote it?

**Comment by pranjalsatija** [comment]
Looks like you [caught](https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/76#discussion_r244882477) it.

**Comment by tylermilner** [comment]
Haha, then it's @wmcginty's fault 100%! 😈

**Comment by wmcginty** [comment]
Dates are hard.

**Pull request merged**
